### ISSUE TITLE
The public service at http://chefdoc.info is down

### ISSUE THREAD

**Issue by mrjcleaver** [chefdoc/chefdoc.info#4]
503

**Comment by joerg** [comment]
Hi,

Thanks for the info. This is a problem with my current hoster which I am going to change very soon. The URL must include a www, so it should be http://www.chefdoc.info/.
When I have some time left (probably during the christmas holidays, maybe earlier) I will migrate to linode. Currently, I can only specify a single domain/subdomain. 🙄
